"""
playground.py - sets up a playground for Notes'n'Todos with predefined notes

MIT license - see LICENSE file in Notes'n'Todos project root

Copyright 2021 - Lars Ole Pontoppidan <contact@larsee.com>
"""

import multiprocessing
import os
import glob
import signal
from threading import Event
from datetime import datetime

exit = Event()

def handleStopSig(signal_no, frame):
    sig = {1:"SIGHUP", 2:"SIGINT", 15:"SIGTERM"}.get(signal_no, "?")
    print(sig + " detected, stopping playground")
    exit.set()

def resetNotesFolder(folder, cycle_time_minutes):
    print("Cleaning up: " + folder)
    
    files = glob.glob(folder + '/*')
    for f in files:
        os.remove(f)

    def writeFile(filename, text):
        print("Writing: " + folder + "/" + filename)
        with open(folder + "/" + filename, "w") as f:
            f.write(text)

    writeFile(datetime.now().strftime('%Y-%m-%d') + " Welcome note.md", 
                welcomeNote % cycle_time_minutes)

    writeFile("2021-03-11 A note about a project.md", 
                projectNote)

    writeFile("2015-10-20 Lorem Markdownum.md", 
                loremMarkdownum)

def runPlayground(folders, start_server_func, cycle_time_minutes):
    # Note, folders should not end with /

    signal.signal(signal.SIGINT, handleStopSig)
    signal.signal(signal.SIGTERM, handleStopSig)
    signal.signal(signal.SIGHUP, handleStopSig)

    print("Resetting playground folders")
    for folder in folders:
        resetNotesFolder(folder, cycle_time_minutes)

    print("Starting server")
    process = multiprocessing.Process(target=start_server_func)
    process.start()

    while True:
        print("Waiting %d minutes before resetting again" % cycle_time_minutes)

        if exit.wait(cycle_time_minutes * 60):
            break

        print("Resetting playground folders")
        for folder in folders:
            resetNotesFolder(folder, cycle_time_minutes)

    print("Killing server")
    process.terminate()
    process.join()

    print("Exiting playground")


# ---- Playground preset notes ----

welcomeNote = """tags: Welcome, Some tag

## Welcome to Notes'n'Todos playground

Go ahead and play around, or read on for more infomation:

*This is a playground. All notes will be deleted and reset every %d minutes.*

*Beware, Notes'n'Todos is intended for single user, glitches may occur if multiple users make changes simultaneously in the playground.*

### Quick start

- Click `Edit` under a note to edit, or click `New Note` to make a new note
- Notes are written in [markdown](https://en.wikipedia.org/wiki/Markdown) syntax
- When done, click `Save Changes` button. Multiple new notes and edits may be saved by one click.
- `date:`, `name:` and `tags:` in the note source declare note date, title and tags
- Date timestamps are formatted according to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601): `YYYY-MM-DD` strictly
- It's **allowed** to change date, name and tags when editing a note 

### Todos

- The **Todos** section shows a summary of all unfinished todos
- **Todo** items are defined in notes using the markdown task list syntax: 
    - `- [ ] Name of task`
    - `- [x] Finished task`
- `Ctrl-d` in the editor makes or toggles todo items on selected lines, same as clicking `Toggle Todo` button
- Todo checkboxes can be **clicked** which will update the note source accordingly

### More hints

- Checking or unchecking tags in the **Tags** section filters what notes to show
- To delete a note, edit it and remove the entire source, then Save Changes
- Notes doesn't need to have `date:`, `tags:` or `name:` lines
- URLs are recognized automatically in the note source
- Links are made with `rel="noreferrer"` in the HTML tag to avoid referring to the note taking app when following links in notes

The notes are stored as plain text files with sensible file names on the server.

### Project links

- https://github.com/larspontoppidan/notesntodos
- https://larsee.com/blog/2021/05/introducing-notesntodos
          
"""

projectNote = """tags: A project, Markdown demo

A table with some considerations:

| Positives | Negatives |
| ----------- | ----------- |
| Line 1      | Text        |
| Line 2      | More text   |

- [ ] Analyse the idea and fill out table with considerations

### First phase of the project

- [ ] Do this
- [ ] Then do that

### Second phase

*Who knows?*
"""


loremMarkdownum = """tags: Lorem Ipsum, Markdown demo

This was generated by: https://jaspervdj.be/lorem-markdownum/

# Data dissimulator dicta amplectitur aetas

## Harenae volunt

Lorem markdownum calamo Phrygiae in rapuit et irascitur grave, uni putant
iussis; quid medio regi omnis obituque peccasse! Nisi viribus numinis, sinus
interea aquas senex plus, Ithaco, dicenti nullo; sucus pater. Corpora tum potes
triplex sororibus quibus coniunx refert somnos de Bacchi. Annis modico colubras
dedit.

1. Ruit Aesoniden doloris paludibus puella lingua qualem
2. Doceo altaque temptatis tempora
3. Canis visa humo renovat fit exitus prius

## Vipereos sacrorum bubus coegi siccaverat felix Doridaque

Parat celsior fertque, dives circumtulit substiterat fleturi ignorat, solacia
discedere et viribus calidumque, Romane salve. Nemus cum Erymanthon calidi
inlisit mea **Procne sortem**, quae siquid? Numquam iaculum texerat sollertia
lacerto frondentis erat: caelestia legem puellari: tantos, mihi inhaesi illo,
non? Tuo *agmen torquetur abest*, incepto omnia constituis enim instare, sua
modo!

## Inducere Aeaciden rigidum terrae aevo

In pennis, *et* pars tristis, ut fleturi robigine omnibus. In gramina ratis,
populi abdita ante staret a votis. Partus festinant **fiducia**, me potuisse
dedit, valvas sparsumque Curetida tot pro ita et corpora eminus haerenti fies?
Stamina freto. Leve simul concipit turbam iungere fauces clam nunc invidiae
miserere *do proles* et igitur totis.

```
    if (lampCapacityHorse) {
        zeroCodeWired = waveform;
    } else {
        upBalance(language, byte_gate / gifPassiveFrequency);
        hardCadAnimated = -5;
        softwareRaw.propertyInternicSerp(gigo, minisite + bsod_reader_drive);
    }
    thermistor += trinitronFont;
    alert = string;
    var sdkCaseParallel = sslBar;
    encoding += association_transistor_system.aix(sector_mask_software);
```

Altera scelerique morte: opus pennis mendacique tempore non luna, gestamina di
Lynceus Astreus. Carmina frondescere parte naturaque ergo, in ne non **pactique
perterrita columnae**. Repulsam at sanguine rursus iaculo; cuius vina sic
Iuppiter, concrescere ramis. Alemoniden exsultatque nata fugatis; et et
praecipiet vultus ignis saxeus; filum ante tenebas, ab nulloque, in. Posito
calorem **iuncta harena**?

## Videre erat sacros eunti obest superest matrem

[Python et](http://tela.io/duxit) quam circa sine est cuspide. Corruit adest
muros solebat **res** vocabis perque quibusque offensi, et! Rauco gaudere malo:
nostro: cum vestem arma tamen: devolvere. Ipse molliet versi tecti sub fortuna
domus. Naxoque **tum** levis tellus nomenque primoque
[eadem](http://tractare.org/spemibi) ad habet sociis.

> Accipit *Nilus coniunx*; iam tulit cruore; patriam senis: patrias Troiae, hoc
> fratri linguaque in. Exit silvis quam colitur graves Triptolemus quem, [erat
> tibi](http://www.quid-totis.net/arvum) Epimethida.

Tabo haut delere, spoliat videbatur terrarum veteres eripe pontus, corpore
iacebitis **atrisque satus quam** Cererem alter ad ubi. Esse [compos
decet](http://fontis.org/fert-verba), onus potest.

*Ipsi Phoebus*, caelo quas, spatium, dederat nequeo; haec quem erat; murmur
glomerabat perii, mea. Arma non patris carpit non caesas, praesensque, mutabile
parit ante nostroque inter remollescit pars; vacuis neu. Statuit leaena anni,
spirantis rector oculos et petiere summis. Corpora occiderat Giganteo antiquum
exstat, dona equidem est non nubilibus sentit. Tantum cubitique flammae, impetus
suos illa tamen tamen dolori conparentis dicentem: quid.
"""
